# Generated by Django 5.1.2 on 2025-01-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstate',
            name='bank_logo',
            field=models.ImageField(upload_to='static/bank_logos/'),
        ),
    ]
