# Generated by Django 5.1.2 on 2025-01-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bankstate_bank_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstate',
            name='bank_operational',
            field=models.BooleanField(default=True),
        ),
    ]
