# Generated by Django 5.1.2 on 2025-01-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookgenre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
