# Generated by Django 5.1.2 on 2025-01-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
