# Generated by Django 5.1.2 on 2025-01-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_logo', models.ImageField(upload_to='bank_logos/')),
                ('bank_operational', models.BooleanField()),
            ],
        ),
    ]
