# Generated by Django 5.1.2 on 2025-01-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowmodel',
            name='balance_after_record',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowmodel',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
