# Generated by Django 5.1.2 on 2024-11-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categorymodel_options_and_more'),
        ('task', '0002_alter_taskmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='tasks',
            field=models.ManyToManyField(related_name='categories', to='task.taskmodel'),
        ),
    ]
