# Generated by Django 5.1.2 on 2024-12-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(upload_to='cars/'),
        ),
    ]
