# Generated by Django 5.1.2 on 2025-01-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userbankaccount_first_name_and_more'),
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='linked_account',
            field=models.ForeignKey(error_messages={'invalid_choice': 'Not a valid account number'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.userbankaccount'),
        ),
    ]
