# Generated by Django 5.1.2 on 2025-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_linked_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='linked_account',
            field=models.IntegerField(null=True),
        ),
    ]
