# Generated by Django 5.1.2 on 2024-10-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicianmodel',
            options={'verbose_name': 'Musician'},
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='f_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='instrument',
            field=models.CharField(max_length=100, verbose_name='Instrument Type'),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='l_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone Number'),
        ),
    ]
