# Generated by Django 5.1.2 on 2025-01-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='first_name',
            field=models.CharField(default=',', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='last_name',
            field=models.CharField(default='.', max_length=50),
            preserve_default=False,
        ),
    ]
