# Generated by Django 5.1.2 on 2024-11-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Task Title')),
                ('desc', models.TextField(verbose_name='Description')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('assign_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
