# Generated by Django 5.1.2 on 2024-11-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_categorymodel_tasks_alter_categorymodel_name'),
        ('task', '0002_alter_taskmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='category.categorymodel'),
        ),
    ]
