# Generated by Django 5.1.2 on 2025-01-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbankaccount_first_name_userbankaccount_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbankaccount',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userbankaccount',
            name='last_name',
        ),
    ]
